### ISSUE TITLE
Importing subscriptions broken (12/31/23)?

### ISSUE THREAD

**Issue by RusselNash10121** [dragos-efy/efy#13]
Hello, I signed up yesterday on https://efy.piped.pages.dev/. Really loving the customization and improvements it offers for the piped UI/UX. Thank you for your work.
I'm using Librewolf (121.0) if that matters.
Unfortunately I am not able to import my subscriptions from either YT or NP. I select the file, it shows the number of subscriptions (122) but when I click import, nothing ever happens (with override selected and not selected). No warning, error out, or message of any kind. I've also tried it connected to / not connected my VPN. Same result either way. Ideas?
(I haven't tried playlists because the instance I have mine on has been down for a day so I haven't been able to export them.)

**Comment by dragos-efy** [comment]
Glad you love it 🔥 I'm assuming it works when you use the [default Piped version](https://piped.video/), right?  I just tried it now on the efy version and it seems to work. I went to `feed` > `subscriptions` > `Import from JSON/CSV` > chose a json file > `import` and the subscriptions and feed showed up. You can try a different browser or logging out of an account if you use one for piped, or using a private window to check if something is interfering with that. It should work on firefox based browsers afaik, but idk if librewolf has issues with it or not.

Also keep in mind that you mentioned YT / NP, so the way the file is exported might not be compatible with piped maybe, in which case you can subscribe to channels manually and export it as json from piped directly for more compatibility in the future, or modify your previous backup file to match the piped format with a text editor in case it doesn't, using a piped subscription backup file as inspiration for how it should look like. Someone mentioned this a few months ago and it worked in that case, maybe it does in yours too.

Also, this repo is for EFY the framework, not piped, but I replied cuz this info might help you haha. You can also ask [EFY questions here](https://matrix.to/#/#efy_ui:matrix.org) or [Piped questions here](https://matrix.to/#/#piped:matrix.org) if you use matrix.

**Comment by RusselNash10121** [comment]
(This is all on Librewolf.)
I can't log in to test it on piped.video and the main instance I was using (kavin.rocks official) I also cannot log in to (that's where my playlists are). So I can't say.
On efy.piped.videos.dev my feed is populated as if my subscriptions are already imported, but the subscriptions page is blank showing 0 subs, which seems contradictory.

Tested with Ungoogled Chromium (120.x) and Falkon (based on Chrome 87.X.
I can not login to piped.video or efy.piped.videos.dev with either of these.

**Comment by RusselNash10121** [comment]
It mentions importing from Newpipe specifically in the import subs page. Why would it mention that if it doesn't work?
I use Libretube as well but the only options it has to export subs is in NP or Freetube format. Neither of those it generates works either.

Also, I don't have Matrix or Telegram. I do have Discord though.

**Comment by RusselNash10121** [comment]
I'll discontinue here and hop over to the piped github page. Thank you for your help.

Seems there are ongoing issues, including the log in issue I mentioned on other instances:

https://github.com/TeamPiped/Piped/issues/3293
