### ISSUE TITLE
Inaccurate position of X button

### ISSUE THREAD

**Issue by DarkCat09** [dragos-efy/efy#5]
Hello.

I'm using Firefox on Android 11.  
In the demo page, close button of an alert has inaccurate positioned X symbol.
***
Screenshot:
![Screenshot_20221121-204452](https://user-images.githubusercontent.com/50486086/203112184-76354ca5-d3e0-487b-9808-c8a723e529d3.png)

**Comment by dragos-efy** [comment]
True, I'll fix it! Thanks!

**Comment by dragos-efy** [comment]
it's fixed now!
